### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by KhOlga** [KhOlga/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ol-kh** [comment]
Self-motivated Junior PHP Developer with 1-year practical experience. Interested in role with the company promoting best practices and offering diverse customer projects. Creat-ed site layout and user interface using HTML5, CSS3, Bootstrap practices. Wrote server-side code for small pet-projects using Symfony framework, Composer, Doctrine ORM, and Twig template. Developed server-side code for Laravel- and Lumen-based web-applications, wrote feature and acceptance tests for the Laravel-based application.
