### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by KhOlga** [KhOlga/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ol-kh** [comment]
E-mail: kharabet.olga@gmail.com
Telegram: @KharabetOlha
www.linkedin.com/in/olha-kharabet-b152125b
Examples of code: https://github.com/KhOlga
