### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by KhOlga** [KhOlga/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ol-kh** [comment]
Skills and knowledge:
- PHP (including OOP, MVC);
- SQL (MySQL);
- Git;
- HTML, HTML5;
- CSS, CSS3;
- Laravel 5.5-7;
- Lumen 7;
- Eloquent ORM;
- Blade;
- Bootstrap 3/4;
- JavaScript; 
- jQuery;
- Composer.

Elementary skills of work with:
- Vue.js;
- PostgreSQL;
- Symfony 4;
- Doctrine ORM;
- Twig;
- Webpack;
- Linux;
- Apache 2;
- npm.

Tools:
- PhpStorm;
- command line;
- MobaXterm.
Languages knowledge:
- Ukrainian: native speaker;
- English: Intermediate;
- German: Pre-Intermediate;
- Russian: Advanced. 

Personal qualities: without bad habits. 

Hobbies: reading; handmade, tailoring.
